# Generated by Django 5.2.13 on 2026-04-24 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Python-разработчик', max_length=150, verbose_name='Название резюме')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО кандидата')),
                ('desired_position', models.CharField(max_length=150, verbose_name='Желаемая должность')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('experience_years', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Опыт работы, лет')),
                ('education', models.TextField(blank=True, verbose_name='Образование')),
                ('skills', models.TextField(help_text='Укажите ключевые навыки через запятую', verbose_name='Навыки')),
                ('work_experience', models.TextField(blank=True, verbose_name='Описание опыта работы')),
                ('about', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('search_status', models.CharField(choices=[('looking', 'Ищет работу'), ('not_looking', 'Не находится в поиске'), ('open_to_offers', 'Рассматривает предложения')], default='looking', max_length=30, verbose_name='Статус поиска')),
                ('visibility', models.CharField(choices=[('public', 'Видно всем'), ('hidden', 'Скрыто')], default='public', max_length=20, verbose_name='Видимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
                'ordering': ['-created_at'],
            },
        ),
    ]
