# Generated by Django 5.2.13 on 2026-04-24 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название вакансии')),
                ('company', models.CharField(max_length=150, verbose_name='Компания')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('employment_type', models.CharField(choices=[('full_time', 'Полная занятость'), ('part_time', 'Частичная занятость'), ('project', 'Проектная работа'), ('internship', 'Стажировка'), ('remote', 'Удалённая работа')], default='full_time', max_length=30, verbose_name='Тип занятости')),
                ('required_experience_years', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Требуемый опыт, лет')),
                ('salary_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата от')),
                ('salary_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата до')),
                ('skills', models.TextField(help_text='Укажите ключевые навыки через запятую', verbose_name='Требуемые навыки')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('requirements', models.TextField(blank=True, verbose_name='Требования к кандидату')),
                ('conditions', models.TextField(blank=True, verbose_name='Условия работы')),
                ('visibility', models.CharField(choices=[('public', 'Видно всем'), ('hidden', 'Скрыто')], default='public', max_length=20, verbose_name='Видимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-created_at'],
            },
        ),
    ]
