# Generated by Django 5.2.13 on 2026-04-24 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
        ('vacancies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Сопроводительное сообщение')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('viewed', 'Просмотрен'), ('accepted', 'Принят'), ('rejected', 'Отклонён')], default='new', max_length=20, verbose_name='Статус отклика')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отклика')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_applications', to=settings.AUTH_USER_MODEL, verbose_name='Соискатель')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='resumes.resume', verbose_name='Резюме')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='vacancies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Отклик на вакансию',
                'verbose_name_plural': 'Отклики на вакансии',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('vacancy', 'resume', 'applicant'), name='unique_application_for_vacancy_resume_applicant')],
            },
        ),
    ]
