# Generated by Django 5.2.13 on 2026-05-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_remove_vacancy_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Ссылка на источник'),
        ),
    ]
