# Generated by Django 5.2.13 on 2026-05-15 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_add_source_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trudvsem_uid', models.CharField(blank=True, max_length=255)),
                ('trudvsem_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_vacancies', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='vacancies.vacancy')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('vacancy__isnull', False)), fields=('user', 'vacancy'), name='unique_user_vacancy_favorite'), models.UniqueConstraint(condition=models.Q(('trudvsem_uid', ''), _negated=True), fields=('user', 'trudvsem_uid'), name='unique_user_trudvsem_favorite')],
            },
        ),
    ]
