# Generated by Django 5.2.13 on 2026-05-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_matchresult_ai_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='relevant_experience_years',
            field=models.FloatField(blank=True, null=True, verbose_name='Релевантный опыт (лет)'),
        ),
    ]
